version: 2.1
jobs:
  compile:
    docker:
      - image: vookimedlo/ubuntu-qt:latestDistroOfficial_gcc_bionic
    steps:
      - checkout
      - run:
          name: compile
          command: |
            /opt/qt/5.13.2/gcc_64/bin/qmake /data/c/ky_gui/ky_gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug && /usr/bin/make qmake_all
      - store_artifacts:
          path: ky_gui
          destination: ky_gui
      - run:
          name: notify_production
          command: |
            curl http://artifact.stronglogicsolutions.com/?artifact=ky_gui

workflows:
 version: 2
 build:
   jobs:
     - compile

