version: 2.1
jobs:
  compile:
    docker:
      - image: logicp/ky_gui:1.0.0
    steps:
      - checkout
      - run:
          name: compile
          command: |
            qmake ky_gui.pro -spec linux-g++ CONFIG+=debug CONFIG+=qml_debug && make -j8
      - store_artifacts:
          path: ky_gui
          destination: ky_gui
      - run:
          name: notify_production
          command: |
            curl http://artifact.stronglogicsolutions.com/?artifact=ky_gui

workflows:
 version: 2
 build:
   jobs:
     - compile

